export const CONTACT_SOURCE_LABELS: Record<string, string> = {
  MANUAL: "Manuell",
  WEBHOOK_GENERIC: "Webhook",
  ZAPIER: "Zapier",
  GOOGLE_ADS: "Google Ads",
  META_LEAD_ADS: "Meta Ads",
  LINKEDIN_LEAD_GEN: "LinkedIn Ads",
  ONEPAGE: "OnePage",
  PERSPEKTIVE: "Perspektive",
  ELEMENTOR: "Elementor",
  TYPEFORM: "TypeForm",
  FUNNELCOCKPIT: "FunnelCockpit",
  HEYFLOW: "HeyFlow",
  MEETOVO: "Meetovo",
  AIDAFORM: "AidaForm",
  THRIVE: "Thrive",
};

export const CONTACT_SOURCE_COLORS: Record<string, string> = {
  MANUAL: "#6B7280",
  WEBHOOK_GENERIC: "#6B7280",
  ZAPIER: "#F97316",
  GOOGLE_ADS: "#4285F4",
  META_LEAD_ADS: "#1877F2",
  LINKEDIN_LEAD_GEN: "#0A66C2",
  ONEPAGE: "#8B5CF6",
  PERSPEKTIVE: "#14B8A6",
  ELEMENTOR: "#92003B",
  TYPEFORM: "#262627",
  FUNNELCOCKPIT: "#111827",
  HEYFLOW: "#4F46E5",
  MEETOVO: "#EC4899",
  AIDAFORM: "#0EA5E9",
  THRIVE: "#16A34A",
};
