-- CreateEnum
CREATE TYPE "OfferCtaType" AS ENUM ('LINK', 'ACCOUNT_MANAGER_REQUEST');

-- AlterTable
ALTER TABLE "Offer" ADD COLUMN "ctaType" "OfferCtaType" NOT NULL DEFAULT 'ACCOUNT_MANAGER_REQUEST';
ALTER TABLE "Offer" ADD COLUMN "ctaUrl" TEXT;
